import {
  collection,
  deleteDoc,
  doc,
  getDocs,
  serverTimestamp,
  writeBatch,
} from 'firebase/firestore';
import { db } from '../firebase/firebaseConfig';

export const deleteAllAccommodations = async () => {
  const accommodationsRef = collection(db, 'accommodations');
  const snapshot = await getDocs(accommodationsRef);

  snapshot.forEach(async (docSnapshot) => {
    await deleteDoc(doc(db, 'accommodations', docSnapshot.id));
  });

  console.log('모든 accommodations 데이터 삭제');
};

export const addAccommodations = async () => {
  const accommodationsRef = collection(db, 'accommodations');
  const batch = writeBatch(db);

  const newAccommodations = [];
  newAccommodations.push(
    {
      description: '누리봄 이야기 농촌 교육농장입니다.',
      capacity: { adults: 3, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '누리봄 이야기 농촌 교육농장',
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '홍길동',
        contact: '055-758-8400',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 35.1667437436642,
        longitude: 127.98933381662154,
        place_name: '경상남도 진주시 대평면 호반로486번길 36-1',
        sub_city: '진주시',
      },
      original_price: '80000',
      rating: 5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv', 'breakfast', 'barbecue'],
      type: 'hotel',
      images: [
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080073&idx=80397',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080073&idx=80398',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080073&idx=80399',
      ],
    },
    {
      description:
        '1988년 서울올림픽 정신을 계승하고 스포츠의 긍정적 가치를 체험할 수 있는 국내 최초 스포츠 체험‧교육기관이다. \r\n스포츠가치센터에서는 생애주기별 맞춤형 체육활동 모델과 미세먼지, 폭염 등 환경적인 요소에 구애받지 않고 신기술을 활용한 스포츠를 체험할 수 있다.\r\n일상생활에서 경험하기 힘든 다양한 스포츠 프로그램을 제공할 예정이며, 체험을 통해 신체 및 정신의 긍정적인 효과를 경험할 수 있다.\r\n학교현장에서 진행이 어려운 기초종목 프로그램 제공으로 스포츠와 함께하는 삶의 전환점을 제공하고, ‘즐기는 스포츠’를 넘어 ‘느끼는 스포츠’를 위한 융합프로그램을 제공한다.\r\n단순 훈련‧숙박시설 제공에서 탈피하여 스포츠과학, 인권 등의 소양교육을 함께 제공하는 학교운동부 전지훈련 장소로 활용하고, 스포츠‧올림픽 가치교육을 통한 인권, 정의 등에 관한 올바른 가치관 정립하는 스포츠체험‧교육기관이다.\r\n다목적 실내스포츠체험관, 운동장, 미니골프장, 양궁장 그리고 약 172명 유스호스텔로 구성된다.(2023년 11월 개관 예정, 개관시기 변동 가능)\r\n\r\n체험시설동 : 다목적실내체육관, 스마트스포츠체험관, 실감영상관, 전시‧휴게 복합공간, 체력인증센터, 정보화실, 강의실 등\r\n편의시설동 : 식당, 매점, 세탁실, 객실(장애인실, 2인실, 3인실) 등\r\n야외시설동 : 다목적야외운동장, 미니골프장, 양궁체험장\r\n',
      capacity: { adults: 1, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: 'KSPO 스포츠가치센터',
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '홍길동',
        contact: '055-790-9350',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 35.1562652772305,
        longitude: 128.034858714962,
        place_name: '경상남도 진주시 내동면 삼계로 360 스포츠가치센터',
        sub_city: '진주시',
      },
      original_price: '80000',
      rating: 4,
      reviews_count: 4,
      services: ['wifi', 'parking', 'tv'],
      type: 'camping',
      images: [
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82167',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82168',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82169',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82170',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82171',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82172',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82173',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82174',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82177',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82175',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080848&idx=82176',
      ],
    },
    {
      description: "Sim's Gallery 입니다.",
      capacity: { adults: 4, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: "Sim's Gallery",
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '산림정원과 정원팀',
        contact: '055-749-4568',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 35.2592864755583,
        longitude: 128.088672743396,
        place_name: '경상남도 진주시 집현면 냉정길279번길 85-8',
        sub_city: '진주시',
      },
      original_price: '80000',
      rating: 4,
      reviews_count: 4,
      services: ['wifi', 'parking', 'tv'],
      type: 'camping',
      images: [
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080739&idx=82268',
      ],
    },
    {
      description:
        '* 주요체험 : 원예체험, 팜스테이, 신토불이 농산물을 이용한 우리 먹거리 만들기(손두부, 인절미, 감 초코파이 등)\r\n* 연계관광지: 광제산(전국 최고의 토종 소나무 숲으로 된 총 연장 20㎞의 웰빙 등산로), \r\n 광제골 고려고분군, 여울당, 소석원, 광제산 봉수대, 집현산, 광제서원, \r\n 진주목공예전수관, 용호정원',
      capacity: { adults: 8, children: 0 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '가뫼골농촌체험휴양마을',
      discount_rate: 0.4,
      final_price: '180000',
      host: {
        name: '홍길동',
        contact: '055-746-2214',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 35.25863836296463,
        longitude: 128.03236369083933,
        place_name: '경상남도 진주시 명석면 관덕길 174',
        sub_city: '진주시',
      },
      original_price: '300000',
      rating: 3.5,
      reviews_count: 4,
      services: ['wifi', 'parking', 'tv', 'breakfast', 'barbecue'],
      type: 'guesthouse',
      images: [
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080071&idx=80386',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080071&idx=80395',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080071&idx=80396',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080071&idx=80387',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=MF00080071&idx=80388',
      ],
    },
    {
      capacity: { adults: 3, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '가좌산',
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '산림과, 가호동 주민센터',
        contact: '055-749-5351, 055-749-4531',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 35.15964208867029,
        longitude: 128.09088186432655,
        place_name: '경상남도 진주시 가좌동',
        sub_city: '진주시',
      },
      original_price: '80000',
      rating: 5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv', 'breakfast', 'barbecue'],
      type: 'camping',
      images: [
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13317',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13318',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13319',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13140',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13179',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13180',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13181',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13184',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13185',
        'http://www.jinju.go.kr/CmsMultiFile/view.do?multifileId=TOUR00606&idx=13186',
      ],
    },
    {
      description:
        '자연, 농촌, 바다가 어우러진 사계절이 아름다운 천사섬 신안군 임자면에 위치<br>4월 튤립축제와 함께 튤립화분, 꽃다발 만들기체험, 대파화분체험, 자연 갯벌에서 생태체험 및 카약 체험, 안전한 생존수영, 양파를 이용한 간식만들기 체험 등 사계절 다양한 체험가능 진로체험 인증기관으로 지정 받아 마을학교 프로그램, 인성학교 프로그램도 진행',
      capacity: { adults: 4, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '임자만났네협동조합',
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '홍길동',
        contact: '061-261-0153',
        experience: '3년',
      },
      location: {
        city: '전라남도',
        latitude: 126.1127281457,
        longitude: 35.0870973161106,
        place_name: '전라남도 신안군 임자면 진리길 44',
        sub_city: '신안군',
      },
      original_price: '80000',
      rating: 4,
      reviews_count: 4,
      services: ['wifi', 'parking', 'tv'],
      type: 'camping',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082148162jMUb',
      ],
    },
    {
      description:
        '넓은 평야와 긴 해안선을 끼고 있어 풍부한 농수산물이 가득한 마을로 칠산대교와 칠산타워, 기독교 순교지가 있음',
      capacity: { adults: 3, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '동촌농어촌체험 휴양마을',
      discount_rate: 0.1,
      final_price: '72000',
      host: {
        name: '산림과, 가호동 주민센터',
        contact: '055-749-5351, 055-749-4531',
        experience: '3년',
      },
      location: {
        city: '경상남도',
        latitude: 126.371152994428,
        longitude: 35.218004687061,
        place_name: '전라남도 영광군 염산면 칠산로 78',
        sub_city: '영광군',
      },
      original_price: '1200000',
      rating: 2.5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv', 'breakfast', 'barbecue'],
      type: 'camping',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081940046f9PL',
      ],
    },
    {
      description:
        '차로 우려낼 수 있는 꽃따기 체험과 채취한 꽃으로 꽃차만들기 체험을 중심으로 체험프로그램을 진행하고 있으며,<br>체험관 숙박시설 이용이 가능한 마을',
      capacity: { adults: 7, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '담양꽃차마을',
      discount_rate: 0.4,
      final_price: '72000',
      host: {
        name: '산림과, 가호동 주민센터',
        contact: '010-3134-3903',
        experience: '3년',
      },
      location: {
        city: '전라남도',
        latitude: 126.921841762639,
        longitude: 35.3733929157499,
        place_name: '전라남도 담양군 월산면 박산길 41',
        sub_city: '담양군',
      },
      original_price: '1200000',
      rating: 2.5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv'],
      type: 'camping',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081940046f9PL',
      ],
    },
    {
      description:
        '촌문화를 살리고자 오감만족 프로그램을 운영<br>복사꽃 살구꽃 피는 시기 축제 개최',
      capacity: { adults: 7, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '월선체험휴양마을',
      discount_rate: 0.2,
      final_price: '1200000',
      host: {
        name: '산림과, 가호동 주민센터',
        contact: '061-452-5556',
        experience: '3년',
      },
      location: {
        city: '전라남도',
        latitude: 126.45630922303,
        longitude: 34.8920009672929,
        place_name: '전라남도 무안군 청계면 예술촌길 148',
        sub_city: '무안군',
      },
      original_price: '1200000',
      rating: 2.5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082015269Qza6',
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082039323ZFEF',
      ],
    },
    {
      description:
        '촌문화를 살리고자 오감만족 프로그램을 운영<br>복사꽃 살구꽃 피는 시기 축제 개최',
      capacity: { adults: 7, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '왕인박사',
      discount_rate: 0.2,
      final_price: '1200000',
      host: {
        name: '홍길동',
        contact: '061-472-0939',
        experience: '3년',
      },
      location: {
        city: '전라남도',
        latitude: 126.627570420348,
        longitude: 34.7608012268228,
        place_name: '전라남도 영암군 군서면 구림로 43-14',
        sub_city: '영암군',
      },
      original_price: '1200000',
      rating: 2.5,
      reviews_count: 5,
      services: ['wifi', 'parking', 'tv'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082231205siKW',
      ],
    },
    {
      description: '남미륵사 등 다양한 볼거리와 쾌적한 숙박시설 완비',
      capacity: { adults: 4, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '탐진사인마을',
      discount_rate: 0.21,
      final_price: '94800',
      host: {
        name: '탐진사인마을 대표',
        contact: '061-433-4244',
        experience: '강진 지역에서 다년간 운영',
      },
      location: {
        city: '전라남도',
        latitude: 126.855759614542,
        longitude: 34.649351915533,
        place_name: '전라남도 강진군 군동면 풍동길 67',
        sub_city: '강진군',
      },
      original_price: '120000',
      rating: 3.3,
      reviews_count: 68,
      services: ['wifi', 'parking'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081544525YGlv',
      ],
    },
    {
      description:
        '농촌의 풍경 속 힐링과 국악체험을 통해 전통의 멋을 느낄 수 있음',
      capacity: { adults: 3, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '사평풍류마을',
      discount_rate: 0.15,
      final_price: '85000',
      host: {
        name: '사평풍류마을 관리자',
        contact: '061-373-4853',
        experience: '화순 전통문화 체험 운영 경험',
      },
      location: {
        city: '전라남도',
        latitude: 127.094735751242,
        longitude: 35.0041312762639,
        place_name: '전라남도 화순군 사평면 사호로 236-40',
        sub_city: '화순군',
      },
      original_price: '100000',
      rating: 4.1,
      reviews_count: 51,
      services: ['parking', 'tv'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082530439jZ1r',
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082512255Bub9',
      ],
    },
    {
      description: '멋과 낭만이 넘치는 사계절 휴양마을',
      capacity: { adults: 5, children: 3 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '신평해울림마을',
      discount_rate: 0.2,
      final_price: '112000',
      host: {
        name: '신평해울림마을 이장',
        contact: '061-844-5000',
        experience: '고흥군 관광체험 운영',
      },
      location: {
        city: '전라남도',
        latitude: 127.177076344119,
        longitude: 34.4901501130189,
        place_name: '전라남도 고흥군 금산면 평산길 90',
        sub_city: '고흥군',
      },
      original_price: '140000',
      rating: 4.0,
      reviews_count: 39,
      services: ['wifi', 'parking'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081619470TwsY',
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/200816486653lCd',
      ],
    },
    {
      description: '봉강 햇살촌은 체험과 숙박이 가능한 자연 속 힐링 공간',
      capacity: { adults: 6, children: 4 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '봉강 햇살촌',
      discount_rate: 0.3,
      final_price: '98000',
      host: {
        name: '봉강햇살촌 대표',
        contact: '061-762-7977',
        experience: '광양시 봉강면 마을 공동체 운영',
      },
      location: {
        city: '전라남도',
        latitude: 127.5655145983,
        longitude: 35.0522220231412,
        place_name: '전라남도 광양시 봉강면 성불로 821',
        sub_city: '광양시',
      },
      original_price: '140000',
      rating: 4.4,
      reviews_count: 76,
      services: ['wifi', 'parking', 'tv'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/200817465756C1G',
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/200818055353FXC',
      ],
    },
    {
      description: '1급수 맑은 물의 발원지, 전통과 자연이 공존하는 마을',
      capacity: { adults: 4, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '개랭이 고들빼기마을',
      discount_rate: 0.18,
      final_price: '82000',
      host: {
        name: '개랭이마을 운영자',
        contact: '061-286-6232',
        experience: '순천시 체험마을 운영',
      },
      location: {
        city: '전라남도',
        latitude: 127.396201499626,
        longitude: 34.8861167357797,
        place_name: '전라남도 순천시 별량면 개령1길 23',
        sub_city: '순천시',
      },
      original_price: '100000',
      rating: 3.7,
      reviews_count: 29,
      services: ['wifi', 'parking'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20082107648hO7f',
      ],
    },
    {
      description: '나주평야 지역의 전형적인 농촌 마을, 힐링 체험 가능',
      capacity: { adults: 5, children: 2 },
      check_in: serverTimestamp(),
      check_out: serverTimestamp(),
      name: '에코왕곡마을',
      discount_rate: 0.24,
      final_price: '95000',
      host: {
        name: '에코왕곡마을 담당자',
        contact: '061-336-6516',
        experience: '나주시 자연순환마을 운영',
      },
      location: {
        city: '전라남도',
        latitude: 126.673148951336,
        longitude: 34.9676179132468,
        place_name: '전라남도 나주시 왕곡면 나주서부로 371-14',
        sub_city: '나주시',
      },
      original_price: '125000',
      rating: 4.2,
      reviews_count: 58,
      services: ['wifi', 'parking'],
      type: 'pension',
      images: [
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081842176P6BV',
        'https://www.namdokorea.com/upload/jeonnam/tour/multimedia/file/2022/06/20081904472Bijq',
      ],
    },
  );

  newAccommodations.forEach((data) => {
    const docRef = doc(accommodationsRef);
    batch.set(docRef, data);
  });

  await batch.commit();
  console.log('새 숙소 데이터 생성');
};
